/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@latticexyz/recs';

export function defineContractComponents(world: World) {
  return {
    Elements: (() => {
      const name = 'Elements';
      return defineComponent(
        world,
        {
          element: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthStatus: (() => {
      const name = 'AuthStatus';
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthRole: (() => {
      const name = 'AuthRole';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
